#!/bin/sh

name="$1"
kt="$2"
vt="${3:-interface{\}}"
hfn="${4:-cmap.DefaultKeyHasher}"
path="${5:-./$name}"
cmapBase="$(go list -f '{{ .Dir }}' github.com/OneOfOne/cmap/internal/cmap 2>/dev/null)"
stripPkg=""
stripHash=""

die() {
	echo $* > /dev/stderr
	exit 1
}

[ -z "$cmapBase" ] && die "couldn't find github.com/OneOfOne/cmap/internal/cmap"
[ -z "$name" -o -z "$kt" ] && die "usage: $0 package-name key-type [value-type|interface{}] [hash-func|cmap.DefaultKeyHasher] [path]"
[ -z "$IS_MAIN_PACKAGE" ] || stripPkg="s/cmap\.//g; s/.*Break =.*//g;"
[ "$hfn" != "cmap.DefaultKeyHasher" ] && stripHash="s/.*[^.]HashFn[ :].*|.*DefaultKeyHasher.*//g; s/cm\.HashFn/$hfn/g;"

echo generating $name $kt $vt $hfn $path

mkdir -p $path

(
	echo "// AUTO-GENERATED by $(basename $0)"
	echo "// DO NOT EDIT";
	echo "// generated from https://github.com/OneOfOne/cmap/tree/master/internal/cmap"; echo; echo
	echo "package $name"; echo

	cat "$cmapBase/cmap.go" "$cmapBase/lmap.go" | perl -ne "\
		s/^package.*$//g; \
		s/^import.*\"$//g; \
		s/KT/$kt/g; \
		s/VT/$vt/g; \
		$stripHash; \
		$stripPkg; \
		print unless /^$/"
) | goimports -e > $path/cmap.go || die

( cd $path && go build ) || die
