#!/bin/sh

name="$1"
kt="$2"
vt="${3:-interface{\}}"
hfn="${4:-cmap.DefaultKeyHasher}"
path="${5:-./$name}"

die() {
	echo $* > /dev/stderr
	exit 1
}

[ -z "$name" -o -z "$kt" ] && die "usage: $0 package-name key-type [value-type|interface{}] [hash-func|cmap.DefaultKeyHasher]"

echo $name $kt $vt $hfn $path

mkdir -p $path

(
	echo "// AUTO-GENERATED by $(basename $0)"
	echo "// DO NOT EDIT"; echo; echo
	perl -ne "\
		s/package cmap/package $name/g; \
		s/KT/$kt/g; \
		s/VT/$vt/g; \
		s/cm\.HashFn/$hfn/g; \
		s/Break/cmap.Break/g; \
		s/DefaultShardCount = .*/DefaultShardCount = cmap.DefaultShardCount/g; \
		print unless /[^.]HashFn[ :]|defaults |the default/gi; \
		" cmap.go
) | goimports -e > $path/cmap.go || die

(
	echo "// AUTO-GENERATED by $(basename $0)"
	echo "// DO NOT EDIT"; echo; echo
	perl -pe "\
		s/package cmap/package $name/g; \
		s/KT/$kt/g; \
		s/VT/$vt/g \
		" lmap.go
) | goimports -e > $path/lmap.go || die

( cd $path && go build -v ) || die
